import React from "react";
import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "./layout";

// Mock the components used in the layout
jest.mock("@/components/Navbar", () => ({
  Navbar: () => <nav data-testid="navbar">Navbar</nav>,
}));

jest.mock("@/components/Footer", () => ({
  Footer: () => <footer data-testid="footer">Footer</footer>,
}));

jest.mock("@/components/PopupWidget", () => ({
  PopupWidget: () => <div data-testid="popup-widget">PopupWidget</div>,
}));

// Mock the ThemeProvider from next-themes
jest.mock("next-themes", () => ({
  ThemeProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock the Inter font import
jest.mock("next/font/google", () => ({
  Inter: () => ({
    className: 'mocked-inter-font',
  }),
}));

describe("RootLayout", () => {
  const mockChildren = <div data-testid="children">Test Children</div>;

  it("renders the layout with all components", () => {
    render(
      <RootLayout>{mockChildren}</RootLayout>
    );

    // Check that children are rendered
    expect(screen.getByTestId("children")).toBeInTheDocument();
    expect(screen.getByText("Test Children")).toBeInTheDocument();

    // Check that all layout components are present
    expect(screen.getByTestId("navbar")).toBeInTheDocument();
    expect(screen.getByTestId("footer")).toBeInTheDocument();
    expect(screen.getByTestId("popup-widget")).toBeInTheDocument();
  });

  it("renders children inside a div container", () => {
    render(
      <RootLayout>{mockChildren}</RootLayout>
    );

    // Verify that children are wrapped in a div as per the layout
    expect(screen.getByTestId("children").parentElement).toBeInTheDocument();
  });
});

describe("metadata", () => {
  it("has correct title and description", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});